---
title: "Alignments into VCF"
output: html_notebook
---

Creating a Function that can turn our alignments into a "VCF"

This needs to be run on hoffman for the fwrite stage. 
```{r include=F,warning=F}

library(tidyverse)
library(data.table)
library(glue)
library(furrr)
library(lubridate)
```



```{r}



divergenceAlignments<-"../data/divergenceAlignments_Oct18.csv"
divergenceAlignments<-as_tibble(fread(divergenceAlignments))
divergenceAlignments<-divergenceAlignments %>% filter( !is.na(numberOfMatches)    | !is.na(numberOfMismatches)  )


createVCFFromAlignment<-function(qLobataChr,qLobataStart,qLobataSeq, qRoburSeq){
qLobataSeq<-str_split(qLobataSeq, "")[[1]]
qRoburSeq<-str_split(qRoburSeq, "")[[1]]
endOfAlignment<-qLobataStart+length(qLobataSeq)-1


vcf<-tibble(
  chr=qLobataChr,
  position=qLobataStart:endOfAlignment,
  qLobataSeq=qLobataSeq,
  qRoburSeq=qRoburSeq
)
return(vcf)
}



l<-list(qLobataChr=divergenceAlignments$QLobata2018Name, qLobataStart=divergenceAlignments$QLobata2018Start, qLobataSeq=divergenceAlignments$pattern, qRoburSeq=divergenceAlignments$subject)

rm(divergenceAlignments)

vcf=pmap_df(l, createVCFFromAlignment)
rm(l)



vcf<-vcf %>% bind_rows()


month<-months(Sys.Date())
day<-day(Sys.Date())
fileName<-glue("../data/vcfOfAlignments_{month}{day}.csv")
#fwrite(vcf, fileName)


```


# Newest Estimate of divergence

```{r}
vcf<-vcf %>% 
  filter(qLobataSeq != "N", 
         qRoburSeq != "N", 
         qLobataSeq != "-", 
         qRoburSeq != "-")

matches<-sum(vcf$qLobataSeq == vcf$qRoburSeq)
mismatches<-sum(vcf$qLobataSeq != vcf$qRoburSeq)

mismatches/(matches+mismatches)
```

